#!/usr/bin/env bash
# shellcheck disable=SC1102,SC1105
#
# Export stdout and stderr into their own variables, and maintain exit code
# Source: https://stackoverflow.com/questions/11027679/capture-stdout-and-stderr-into-different-variables
# Usage:
# $ catch ACTUAL_STDOUT ACTUAL_STDERR my_command
catch() {
    {
        IFS=$'\n' read -r -d '' "${1}";
        IFS=$'\n' read -r -d '' "${2}";
        (IFS=$'\n' read -r -d '' _ERRNO_; return ${_ERRNO_});
    } < <((printf '\0%s\0%d\0' "$(((({ shift 2; "${@}"; echo "${?}" 1>&3-; } | tr -d '\0' 1>&4-) 4>&2- 2>&1- | tr -d '\0' 1>&4-) 3>&1- | exit "$(cat)") 4>&1-)" "${?}" 1>&2) 2>&1)
}
