version: 2

jobs:
  build:
    docker:
      # To know the correct sha, trigger a dummy build with
      # circleci/node:latest, and check the logs for the full sha
      - image: circleci/node@sha256:91bdc627e3c06298c8edc6c5030429401c81819acc2f3784765f8ae555775ebf
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - run: 'yarn install'
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: 'yarn run ci'
