#!/usr/bin/env bash
# This is a very simple test framework, to test at the CLI level that our "yarn
# test" command actually work as expected
#
# A typical test file should look like:
#
# test "name of the test"
# actual() {
#   # Code of the method to run
# }
#
# Add any expectation
# expect_to_fail
# expect_to_succeed

# Default testName is empty, but define it with test
testName=""
test() {
	echo "Running..."
	testName=$1
}
# End the test as a success
success() {
	echo "✔ $testName"
	exit 0
}
# End the test as a failure
failure() {
	echo "✗ $testName"
	exit 1
}

# Check the exitCode, and expect it to succeed
expect_to_succeed() {
	if actual >/dev/null; then
		success
	else
		failure
	fi
}

# Check the exitCode, and expect it to fail
expect_to_fail() {
	if actual >/dev/null; then
		failure
	else
		success
	fi
}
