#!/usr/bin/env sh
# We cannot use `aberlaas build` to build itself, so we revert to good old
# scripts
set -e

# When SKIP_BUILD is set to true, we skip the whole script
# This is used in ./scripts/ci to avoid running the build script over and over
# again for each script invoked by the CI
[ -n "$SKIP_BUILD" ] && exit 0


mkdir -p ./build

babel \
  ./lib/ \
  --verbose \
  --ignore "lib/**/__tests__" \
  --ignore "lib/**/test-helper.js" \
  --out-dir ./build
