#!/usr/bin/env sh
# We cannot use `aberlaas build` to build itself, so we revert to good old
# scripts
set -e

mkdir -p ./build

babel \
  ./lib/ \
  --verbose \
  --ignore "lib/**/__tests__" \
  --ignore "lib/**/test-helper.js" \
  --out-dir ./build

