#!/usr/bin/env sh
# We cannot use `aberlaas build` to build itself
set -e

mkdir -p ./build

babel \
  ./lib/ \
  --ignore "lib/__tests__" \
  --ignore "lib/test-helper.js" \
  --out-dir ./build \
  --watch \
  --verbose \
  --source-maps inline
